cc: CreditCardMain.cpp
	g++ -std=c++11 -W -Wall -pedantic CreditCardMain.cpp -o cc

pp: PersonMain.cpp
	g++ -W -Wall -pedantic PersonMain.cpp -o pp

hp: HarmProgressionMain.cpp
	g++ -std=c++11 -W -Wall -pedantic HarmProgressionMain.cpp -o hp